import React from "react";
import { AlertCircle } from "lucide-react";
export const priorityClass={RED:"bg-red-50 text-red-700 border-red-200",YELLOW:"bg-amber-50 text-amber-700 border-amber-200",GREEN:"bg-emerald-50 text-emerald-700 border-emerald-200"};
export function PriorityBadge({level}){return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-bold ${priorityClass[level]||priorityClass.GREEN}`}><span className="h-2 w-2 rounded-full bg-current"/>{level}</span>}
export function StatusBadge({status}){return <span className={`inline-flex rounded-full border px-2.5 py-1 text-xs font-semibold ${status==="COMPLETED"?"border-emerald-200 bg-emerald-50 text-emerald-700":status==="EN ROUTE"||status==="RESPONDING"?"border-blue-200 bg-blue-50 text-blue-700":"border-slate-200 bg-slate-50 text-slate-700"}`}>{status}</span>}
export function Card({children,className=""}){return <div className={`rounded-2xl border border-slate-200/80 bg-white shadow-[0_12px_40px_-28px_rgba(30,64,175,.28)] transition-shadow duration-200 ${className}`}>{children}</div>}
export function Button({children,className="",variant="primary",...props}){const styles={primary:"bg-[#4f7df3] text-white hover:bg-[#3d67d8] shadow-sm shadow-blue-200/50",blue:"bg-[#4f7df3] text-white hover:bg-[#3d67d8] shadow-sm shadow-blue-200/50",danger:"bg-[#4f7df3] text-white hover:bg-[#3d67d8] shadow-sm shadow-blue-200/50",secondary:"bg-white text-slate-700 border border-slate-200 hover:border-blue-200 hover:bg-blue-50/50",ghost:"bg-transparent text-slate-600 hover:bg-slate-100"};return <button className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition duration-200 active:scale-[.99] disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`} {...props}>{children}</button>}
export function Metric({label,value,hint,icon:Icon,trend}){return <Card className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 text-3xl font-black text-slate-950">{value}</p>{hint&&<p className="mt-1 text-xs text-slate-500">{hint}</p>}{trend&&<p className="mt-2 text-xs font-bold text-emerald-600">{trend}</p>}</div>{Icon&&<div className="rounded-xl bg-blue-50 p-2.5 text-[#4f7df3]"><Icon size={18}/></div>}</div></Card>}
export function EmptyState({title,text,icon:Icon=AlertCircle}){return <div className="grid place-items-center rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center"><Icon className="text-slate-400"/><h3 className="mt-3 font-bold">{title}</h3><p className="mt-1 text-sm text-slate-500">{text}</p></div>}
export function StepHeader({step,title,text}){return <div><div className="flex items-center gap-2 text-xs font-extrabold uppercase tracking-[.15em] text-[#4f7df3]"><span>0{step}</span><span className="h-px w-8 bg-blue-200"/><span>RapidRescue response flow</span></div><h1 className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-slate-500">{text}</p></div>}
