import React, { createContext, useCallback, useContext, useMemo, useState } from "react";
import { demoUsers, demoAmbulances, demoHospitals, demoHelpers, demoEmergencies } from "../data/demo";
import { priorityEngine } from "../services/priorityService";
const KEY = "ers-demo-state-v2";
const defaultState = { currentUser:null, users:demoUsers, ambulances:demoAmbulances, hospitals:demoHospitals, helpers:demoHelpers, emergencies:demoEmergencies, notifications:[], draft:{type:"",details:"",location:null,answers:{}} };
function freshState(){ return JSON.parse(JSON.stringify(defaultState)); }
function load(){ try{return JSON.parse(localStorage.getItem(KEY))||freshState()}catch{return freshState()} }
function save(state){localStorage.setItem(KEY,JSON.stringify(state));}
const Ctx=createContext(null);
export function AppProvider({children}){
 const [state,setState]=useState(load); const persist=useCallback(next=>{setState(next);save(next)},[]); const reloadFromStorage=useCallback(()=>setState(load()),[]);
 const login=useCallback(user=>persist({...load(),currentUser:user}),[persist]);
 const logout=useCallback(()=>persist({...load(),currentUser:null}),[persist]);
 const resetDemo=useCallback(()=>persist(freshState()),[persist]);
 const notify=useCallback((message,tone="info",duration=3000)=>{const current=load();const id=crypto.randomUUID();const now=Date.now();persist({...current,notifications:[{id,message,tone,at:now,expiresAt:now+duration},...current.notifications].slice(0,12)})},[persist]);
 const removeNotification=useCallback(id=>{const current=load();persist({...current,notifications:current.notifications.filter(n=>n.id!==id)})},[persist]);
 const setDraft=useCallback(patch=>{const current=load();persist({...current,draft:{...current.draft,...patch}})},[persist]);
 const updateUser=useCallback((userId,patch)=>{const current=load();const users=current.users.map(u=>u.id===userId?{...u,...patch,helperProfile:patch.helperProfile?{...u.helperProfile,...patch.helperProfile}:u.helperProfile}:u);persist({...current,users,currentUser:current.currentUser?.id===userId?users.find(u=>u.id===userId):current.currentUser})},[persist]);
 const setHelperAvailability=useCallback(enabled=>{const current=load();const userId=current.currentUser?.id;if(!userId)return;const users=current.users.map(u=>u.id===userId?{...u,helperProfile:{...u.helperProfile,enabled,availability:enabled?"AVAILABLE":"OFFLINE",responseStatus:enabled?"AVAILABLE":"OFFLINE"}}:u);const helpers=current.helpers.map(h=>h.id==="helper-1"&&userId==="u-citizen"?{...h,availability:enabled?"AVAILABLE":"OFFLINE"}:h);persist({...current,users,currentUser:users.find(u=>u.id===userId),helpers})},[persist]);
 const respondToHelperRequest=useCallback((emergencyId,response)=>{const current=load();const helperId=current.currentUser?.id||"u-citizen";const profile=current.users.find(u=>u.id===helperId)?.helperProfile||{};const status=response==="accept"?"ACCEPTED":response==="enroute"?"EN ROUTE":response==="arrived"?"ARRIVED":"UNABLE TO HELP";const label=response==="accept"?"Helper accepted":response==="enroute"?"Helper en route":response==="arrived"?"Helper arrived":"Helper declined";const emergencies=current.emergencies.map(e=>e.id===emergencyId?{...e,helperId:response==="decline"?null:helperId,helperStatus:status,events:[...e.events,{label,at:Date.now()}]}:e);const users=current.users.map(u=>u.id===helperId?{...u,helperProfile:{...profile,availability:response==="decline"?"AVAILABLE":response==="arrived"?"ON SCENE":"RESPONDING",responseStatus:status}}:u);const helpers=current.helpers.map(h=>h.id===helperId||(helperId==="u-citizen"&&h.id==="helper-1")?{...h,availability:response==="decline"?"AVAILABLE":"RESPONDING",responseStatus:status}:h);persist({...current,users,currentUser:users.find(u=>u.id===helperId),helpers,emergencies})},[persist]);
 const createEmergency=useCallback(()=>{const current=load();const score=priorityEngine(current.draft.answers);const hospital=current.hospitals.slice().sort((a,b)=>a.distanceKm-b.distanceKm)[0];const ambulance=current.ambulances.filter(a=>a.status==="AVAILABLE").sort((a,b)=>a.distanceKm-b.distanceKm)[0];const id=`ER-${Math.floor(1000+Math.random()*8999)}`;const now=Date.now();const emergency={id,type:current.draft.type||"Emergency Assistance",details:current.draft.details,location:current.draft.location||{lat:28.6139,lng:77.209,address:"Demo Emergency Location",accuracy:18},priority:score.level,score:score.score,reasons:score.reasons,status:"REPORTED",createdAt:now,ambulanceId:ambulance?.id||null,helperId:null,helperStatus:null,hospitalId:hospital?.id||null,eta:ambulance?Math.max(3,Math.round(ambulance.distanceKm*2)):null,events:[{label:"Reported",at:now},{label:"Priority assessed",at:now+50}]};const ambulances=ambulance?current.ambulances.map(a=>a.id===ambulance.id?{...a,status:"ASSIGNED",currentEmergencyId:id}:a):current.ambulances;persist({...current,emergencies:[emergency,...current.emergencies],ambulances,draft:{type:"",details:"",location:null,answers:{}}});return emergency},[persist]);
 const updateEmergency=useCallback((id,patch,eventLabel)=>{const current=load();persist({...current,emergencies:current.emergencies.map(e=>e.id===id?{...e,...patch,events:eventLabel?[...e.events,{label:eventLabel,at:Date.now()}]:e.events}:e)})},[persist]);
 const updateAmbulance=useCallback((id,patch)=>{const current=load();persist({...current,ambulances:current.ambulances.map(a=>a.id===id?{...a,...patch}:a)})},[persist]);
 const value=useMemo(()=>({...state,login,logout,resetDemo,notify,removeNotification,setDraft,createEmergency,updateEmergency,updateAmbulance,updateUser,respondToHelperRequest,setHelperAvailability,reloadFromStorage}),[state,login,logout,resetDemo,notify,removeNotification,setDraft,createEmergency,updateEmergency,updateAmbulance,updateUser,respondToHelperRequest,setHelperAvailability,reloadFromStorage]);
 return <Ctx.Provider value={value}>{children}</Ctx.Provider>;
}
export function useApp(){return useContext(Ctx)}
